version: '3.9'
name: vocaplace

services:

  # client:
  #   build: client
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - REACT_APP_SERVER_PORT=8000
  #     - REACT_APP_KEYCLOAK_PORT=8080
  #     - REACT_APP_KEYCLOAK_REALM=react-app
  #     - REACT_APP_KEYCLOAK_CLIENT_ID=app-frontend
  #   depends_on:
  #     - server
  #     - keycloak

  server:
    build: ./server
    command: npm run dev
    ports:
      - '8000:8000'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=vocaplace
      - DB_PORT=5432
      - DB_SERVICE_NAME=db
      - NODE_ENV=development
      - SERVER_PORT=8000
      - KEYCLOAK_PORT=8080
      - CLIENT_PORT=3000
      - KEYCLOAK_REALM=react-app
      - KEYCLOAK_CLIENT_ID=app-backend
      - KEYCLOAK_REALM_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApwGevzUGP555SMHPKbDlZFAjbyzH9EIEq4JJa7qH5tm4tCUZJBIDfroZClrkPpDJ32ZP+j+Pv4aLLVZx//v3ungrxKZVO7SIZjaO/qt6a1CDzjRhRMR/wxWZiqpfxEvzCfScNR9DmzfatSip9Z8jgEzaFk3TXin49F0BPCsbqG/f2DXmwbGKoaM8Eh0+2WaD4OnlmTB04AJVmaKx23z30imtf+0nCu+gcoLGKzZkVH2lZOXqXIP66xTGwuN981Hl5j52I0XDXZaU3xlfdp1agLNQcHd7M7TeyzHS3xVmusJbzDacktptg21JF7+9FEFLTw9youRH6eEwKaqxRsX0qwIDAQAB
    develop:
      watch:
        - action: sync
          path: ./server
          target: /opt/app
          ignore:
            - node_modules
        - action: rebuild
          path: ./server/package.json
    depends_on:
      - db
      - keycloak

  db:
    image: postgres:16-alpine3.18
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./server/src/db/sql/setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vocaplace
    # tmpfs: /var/lib/postgresql/data # temporary, data wont save

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/data:/opt/keycloak/data/h2
      - ./keycloak/themes:/opt/keycloak/themes/
    command: start-dev

volumes:
  postgres:
