version: '3.9'

services:
  client:
    build: client
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    build: ./server
    command: npm run start
    ports:
      - '8000:8000'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=duolingo
      - DB_PORT=5432
      - DB_SERVICE_NAME=db
      - PORT=8000
    volumes:
      - ./server/:/opt/app
    depends_on:
      - db
    
  db:
    image: postgres:16-alpine3.18
    volumes:
      - zesp-postgres:/var/lib/postgresql/data/
      - ./server/db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=duolingo

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/data:/opt/keycloak/data/h2
      - ./keycloak/themes:/opt/keycloak/themes/
    command: start-dev

volumes:
  zesp-postgres:
