version: '3.9'

services:
  server:
    build: .
    command: npm run start
    ports:
      - '8000:8000'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=duolingo
      - DB_PORT=5432
      - DB_SERVICE_NAME=db
      - PORT=8000
    volumes:
      - ./:/opt/app
    depends_on:
      - db
    
  db:
    image: postgres:16-alpine3.18
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=duolingo